server:
  port: 8081
  servlet:
    context-path: '/external'
spring:
  profiles:
    active: ${SPRING_FROFILES_INCLUDE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://127.0.0.1:8888}
  cloud:
    config:
      label: ${SPRING_CLOUD_COFIG_LABEL:master}
      username: ${SPRING_CLOUD_COFIG_USERNAME:geek_user}
      password: ${SPRING_CLOUD_COFIG_PASSWORD:geek_pass}

arborum.api:
  endpoint:
    manufacturer-url: 'http://${arborum.api.endpoint.base-url}/api/v1/manufacturer'
  connection:
    period: 100
    max-period: 10000 #Millis
    max-attempts: 3
    connect-timeout: 10000 #Millis
    #    connect-timeout-unit:
    read-timeout: 30000 #Millis
    #    read-timeout-unit:
    follow-redirects: true