server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_FROFILES_INCLUDE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://127.0.0.1:8888}
  cloud:
    config:
      label: ${SPRING_CLOUD_COFIG_LABEL:master}
      username: ${SPRING_CLOUD_COFIG_USERNAME:geek_user}
      password: ${SPRING_CLOUD_COFIG_PASSWORD:geek_pass}